import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { nextCookies, toNextJsHandler } from "better-auth/next-js";
import { admin } from "better-auth/plugins";
import { createAccessControl } from "better-auth/plugins/access";

import { db } from "@/lib/db";
import { ADMIN_ROLE, STAFF_ROLE } from "@/lib/roles";

/**
 * Access-control statements for the admin plugin, under this project's own
 * role names rather than the plugin's built-in `admin`/`user` defaults (see
 * `src/lib/roles.ts`). The permission sets are copied unchanged from
 * `better-auth/plugins/admin`'s own `defaultStatements`/`adminAc`/`userAc` —
 * `ADMIN_ROLE` keeps every default admin permission, `STAFF_ROLE` keeps the
 * default non-admin's (none).
 *
 * Spelling this out explicitly, instead of leaving `admin()`'s `roles`
 * option unset and relying on its built-in defaults, does two things the
 * defaults alone would not:
 *
 *   1. Types `auth.api.createUser`'s `role` field (and every other
 *      role-accepting call) as `"admin" | "staff"` — with no custom `roles`
 *      map, `InferAdminRolesFromOption` stays anchored to the built-in
 *      `"admin" | "user"`, and `role: "staff"` fails to type-check.
 *   2. Turns on `/admin/create-user`'s own validation that a requested role
 *      actually exists (`opts.roles && !opts.roles[role]`): with no `roles`
 *      map configured, that check does not run at all, and the endpoint
 *      would silently accept any string as a role.
 */
const accessControlStatements = {
  user: [
    "create",
    "list",
    "set-role",
    "ban",
    "impersonate",
    "impersonate-admins",
    "delete",
    "set-password",
    "set-email",
    "get",
    "update",
  ],
  session: ["list", "revoke", "delete"],
} as const;

const accessControl = createAccessControl(accessControlStatements);

const adminAccess = accessControl.newRole({
  user: [
    "create",
    "list",
    "set-role",
    "ban",
    "impersonate",
    "delete",
    "set-password",
    "set-email",
    "get",
    "update",
  ],
  session: ["list", "revoke", "delete"],
});

const staffAccess = accessControl.newRole({
  user: [],
  session: [],
});

/**
 * Global rate-limit window and ceiling, in seconds and request count. This
 * is the library's own default (`rateLimit.window || 10`, `rateLimit.max ||
 * 100` in `better-auth`'s `create-context.mjs`) — stated here explicitly so
 * the value is visible at the call site rather than inherited silently.
 * Ticket #111.
 */
const RATE_LIMIT_WINDOW_SECONDS = 10;
const RATE_LIMIT_MAX_REQUESTS = 100;

/**
 * Server-side Better Auth configuration. Together with `auth-client.ts` this is
 * the only place the library is configured (ADR 0002), so a change of
 * persistence layer or of authentication library stays inside two files.
 *
 * Level 1 of the ADR 0002 ladder: the built-in `better-auth/adapters/prisma`
 * adapter, handed the Prisma 7 client that `src/lib/db.ts` builds from the
 * generated output in `src/generated/prisma`. The library's documentation still
 * shows `import { PrismaClient } from "@prisma/client"`; only the import path
 * differs, and the adapter itself is indifferent to where the client came from.
 *
 * `secret` and `baseURL` are read from `BETTER_AUTH_SECRET` and
 * `BETTER_AUTH_URL` by the library, so they are not restated here.
 *
 * `emailAndPassword.disableSignUp` closes the public `/sign-up/email`
 * endpoint (FR-1.1: no public self-registration). It does not touch the
 * admin plugin's own `/admin/create-user` endpoint — that route has no
 * reference to this flag at all — which is how an admin still creates
 * accounts through `auth.api.createUser`.
 *
 * `admin({ ac, roles, defaultRole, adminRoles })` maps this product's two
 * roles (`src/lib/roles.ts`) onto the plugin's own role model rather than
 * adding a parallel one. `adminRoles` says `ADMIN_ROLE` is the elevated
 * role; `defaultRole` says an admin-created account with no explicit role
 * starts as `STAFF_ROLE`. Because `STAFF_ROLE` carries no permissions in the
 * `roles` map above, every permission check the plugin runs against it
 * fails closed — a staff caller is refused by the library itself, before
 * `src/lib/require-user.ts`'s own check ever runs. See
 * `scripts/verify-admin-role-model.ts` for the empirical proof against the
 * installed `better-auth@1.7.1`.
 *
 * `rateLimit.storage: "database"` (ticket #111) moves the request counter
 * off the in-process `Map` that is `better-auth`'s own "memory" default
 * (`node_modules/better-auth/dist/api/rate-limiter/index.mjs`) and into the
 * `rateLimit` Prisma model, generated by `npm run auth:generate`. On a
 * serverless platform each warm instance otherwise keeps its own counter,
 * lost on every cold start; a database-backed counter is shared and durable
 * application-wide. `window`/`max` restate the library's own default
 * (`10` seconds / `100` requests — `create-context.mjs`) explicitly rather
 * than leaving it to inherit silently. The stricter special rule on
 * `/sign-in`, `/sign-up`, `/change-password` and `/change-email` (`10`
 * seconds / `3` requests) is hardcoded inside `better-auth` itself
 * (`getDefaultSpecialRules`) — it is not read from any option, so there is
 * no config key to restate it through — and it now rides the same database
 * storage backend as the global rule above.
 *
 * `enabled` is left unset on purpose: it defaults to `isProduction`, which
 * is what keeps sign-in usable during local development. A test of this
 * behaviour has to pass `rateLimit: { enabled: true }` itself.
 */
const RATE_LIMIT = {
  storage: "database",
  window: RATE_LIMIT_WINDOW_SECONDS,
  max: RATE_LIMIT_MAX_REQUESTS,
} as const;

export const auth = betterAuth({
  database: prismaAdapter(db, { provider: "postgresql" }),
  emailAndPassword: {
    enabled: true,
    disableSignUp: true,
  },
  rateLimit: RATE_LIMIT,
  // `nextCookies` has to stay last in the list: it converts the cookies the
  // preceding plugins set into Next.js cookie writes.
  plugins: [
    admin({
      ac: accessControl,
      roles: { [ADMIN_ROLE]: adminAccess, [STAFF_ROLE]: staffAccess },
      defaultRole: STAFF_ROLE,
      adminRoles: [ADMIN_ROLE],
    }),
    nextCookies(),
  ],
});

/**
 * The route handler pair mounted at `/api/auth/[...all]`. It is built here
 * rather than in the route file so that `better-auth` keeps a single import
 * site on the server, as the seam rules require.
 */
export const authRouteHandlers = toNextJsHandler(auth);
