import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { APIError, createAuthMiddleware, isAPIError } from "better-auth/api";
import { nextCookies, toNextJsHandler } from "better-auth/next-js";
import { admin } from "better-auth/plugins";
import { createAccessControl } from "better-auth/plugins/access";

import { db } from "@/lib/db";
import { ADMIN_ROLE, STAFF_ROLE } from "@/lib/roles";
import {
  readSignInLockState,
  recordSignInAttempt,
} from "@/lib/sign-in-attempts";
import { classifySignInOutcome, readSignInEmail } from "@/lib/sign-in-lockout";

/**
 * Access-control statements for the admin plugin, under this project's own
 * role names rather than the plugin's built-in `admin`/`user` defaults (see
 * `src/lib/roles.ts`). The permission sets are copied unchanged from
 * `better-auth/plugins/admin`'s own `defaultStatements`/`adminAc`/`userAc` —
 * `ADMIN_ROLE` keeps every default admin permission, `STAFF_ROLE` keeps the
 * default non-admin's (none).
 *
 * Spelling this out explicitly, instead of leaving `admin()`'s `roles`
 * option unset and relying on its built-in defaults, does two things the
 * defaults alone would not:
 *
 *   1. Types `auth.api.createUser`'s `role` field (and every other
 *      role-accepting call) as `"admin" | "staff"` — with no custom `roles`
 *      map, `InferAdminRolesFromOption` stays anchored to the built-in
 *      `"admin" | "user"`, and `role: "staff"` fails to type-check.
 *   2. Turns on `/admin/create-user`'s own validation that a requested role
 *      actually exists (`opts.roles && !opts.roles[role]`): with no `roles`
 *      map configured, that check does not run at all, and the endpoint
 *      would silently accept any string as a role.
 */
const accessControlStatements = {
  user: [
    "create",
    "list",
    "set-role",
    "ban",
    "impersonate",
    "impersonate-admins",
    "delete",
    "set-password",
    "set-email",
    "get",
    "update",
  ],
  session: ["list", "revoke", "delete"],
} as const;

const accessControl = createAccessControl(accessControlStatements);

const adminAccess = accessControl.newRole({
  user: [
    "create",
    "list",
    "set-role",
    "ban",
    "impersonate",
    "delete",
    "set-password",
    "set-email",
    "get",
    "update",
  ],
  session: ["list", "revoke", "delete"],
});

const staffAccess = accessControl.newRole({
  user: [],
  session: [],
});

/**
 * Global rate-limit window and ceiling, in seconds and request count. This
 * is the library's own default (`rateLimit.window || 10`, `rateLimit.max ||
 * 100` in `better-auth`'s `create-context.mjs`) — stated here explicitly so
 * the value is visible at the call site rather than inherited silently.
 * Ticket #111.
 */
const RATE_LIMIT_WINDOW_SECONDS = 10;
const RATE_LIMIT_MAX_REQUESTS = 100;

/**
 * Server-side Better Auth configuration. Together with `auth-client.ts` this is
 * the only place the library is configured (ADR 0002), so a change of
 * persistence layer or of authentication library stays inside two files.
 *
 * Level 1 of the ADR 0002 ladder: the built-in `better-auth/adapters/prisma`
 * adapter, handed the Prisma 7 client that `src/lib/db.ts` builds from the
 * generated output in `src/generated/prisma`. The library's documentation still
 * shows `import { PrismaClient } from "@prisma/client"`; only the import path
 * differs, and the adapter itself is indifferent to where the client came from.
 *
 * `secret` and `baseURL` are read from `BETTER_AUTH_SECRET` and
 * `BETTER_AUTH_URL` by the library, so they are not restated here.
 *
 * `emailAndPassword.disableSignUp` closes the public `/sign-up/email`
 * endpoint (FR-1.1: no public self-registration). It does not touch the
 * admin plugin's own `/admin/create-user` endpoint — that route has no
 * reference to this flag at all — which is how an admin still creates
 * accounts through `auth.api.createUser`.
 *
 * `admin({ ac, roles, defaultRole, adminRoles })` maps this product's two
 * roles (`src/lib/roles.ts`) onto the plugin's own role model rather than
 * adding a parallel one. `adminRoles` says `ADMIN_ROLE` is the elevated
 * role; `defaultRole` says an admin-created account with no explicit role
 * starts as `STAFF_ROLE`. Because `STAFF_ROLE` carries no permissions in the
 * `roles` map above, every permission check the plugin runs against it
 * fails closed — a staff caller is refused by the library itself, before
 * `src/lib/require-user.ts`'s own check ever runs. See
 * `scripts/verify-admin-role-model.ts` for the empirical proof against the
 * installed `better-auth@1.7.1`.
 *
 * `rateLimit.storage: "database"` (ticket #111) moves the request counter
 * off the in-process `Map` that is `better-auth`'s own "memory" default
 * (`node_modules/better-auth/dist/api/rate-limiter/index.mjs`) and into the
 * `rateLimit` Prisma model, generated by `npm run auth:generate`. On a
 * serverless platform each warm instance otherwise keeps its own counter,
 * lost on every cold start; a database-backed counter is shared and durable
 * application-wide. `window`/`max` restate the library's own default
 * (`10` seconds / `100` requests — `create-context.mjs`) explicitly rather
 * than leaving it to inherit silently. The stricter special rule on
 * `/sign-in`, `/sign-up`, `/change-password` and `/change-email` (`10`
 * seconds / `3` requests) is hardcoded inside `better-auth` itself
 * (`getDefaultSpecialRules`) — it is not read from any option, so there is
 * no config key to restate it through — and it now rides the same database
 * storage backend as the global rule above.
 *
 * `enabled` is left unset on purpose: it defaults to `isProduction`, which
 * is what keeps sign-in usable during local development. A test of this
 * behaviour has to pass `rateLimit: { enabled: true }` itself.
 *
 * `hooks` carries the account lockout (ticket #112) — see
 * `signInLockoutBefore` and `signInLockoutAfter` below. Unlike `rateLimit`, it
 * is on in every environment: the threshold is five consecutive failures, which
 * development never reaches by accident, and a lockout that only exists in
 * production is a lockout nobody exercises before it matters.
 */
const RATE_LIMIT = {
  storage: "database",
  window: RATE_LIMIT_WINDOW_SECONDS,
  max: RATE_LIMIT_MAX_REQUESTS,
} as const;

/** The one endpoint the lockout hooks below act on. */
const SIGN_IN_EMAIL_PATH = "/sign-in/email";

/**
 * The rejection a locked address gets, and the reason it is built with
 * `APIError.from` rather than `new APIError`.
 *
 * Issue #112 requires a lock to be *indistinguishable* from a wrong password,
 * so the response has to match the one `dist/api/routes/sign-in.mjs` produces —
 * which throws
 * `APIError.from("UNAUTHORIZED", BASE_ERROR_CODES.INVALID_EMAIL_OR_PASSWORD)`.
 * Rebuilding that as `new APIError("UNAUTHORIZED", { code, message })` would
 * match in status and in content and still differ on the wire: `from` builds
 * its body as `{ message, code }` and `JSON.stringify` preserves insertion
 * order, so a hand-built body with the keys the other way round serialises to
 * different bytes. The same factory removes that class of mistake.
 *
 * `BASE_ERROR_CODES` is not reachable — it lives in `@better-auth/core`, a
 * transitive dependency this project does not declare — so the two strings are
 * restated here, as `accessControlStatements` above restates the admin
 * plugin's defaults. `scripts/verify-sign-in-lockout.ts` asserts they still
 * match `auth.$ERROR_CODES.INVALID_EMAIL_OR_PASSWORD` at runtime, so a
 * library-side rename fails loudly rather than quietly reopening the oracle.
 */
const CREDENTIALS_REJECTED = {
  code: "INVALID_EMAIL_OR_PASSWORD",
  message: "Invalid email or password",
} as const;

/**
 * Refuses a sign-in against an address that is currently locked out (issue
 * #112, and section 6 / F-02 of `docs/security-review-2026-08-27.md`).
 *
 * **Why `hooks.before` is the interception point.** Better Auth 1.7.1 has no
 * lockout primitive, and of the three places a lockout could attach this is the
 * only one that can refuse an attempt *before* the password is checked.
 * `databaseHooks.session.create.before` — where the admin plugin's `banned`
 * gate sits — runs only after the credential verified, which is too late to
 * bound guessing. A plugin would work but buys nothing here: `hooks.before` is
 * a documented top-level option (`hooks?: { before?: AuthMiddleware }` in
 * `@better-auth/core`'s `init-options`), and `dist/api/dispatch.ts` runs the
 * user's hook ahead of every plugin's.
 *
 * The hook is registered for every endpoint — `getHooks` gives a user hook the
 * matcher `() => true` — so the path test is the first statement and costs one
 * string comparison on requests this has nothing to do with.
 *
 * **The refusal short-circuits before any password hashing, on purpose.** A
 * blocked attempt is therefore measurably faster to answer than a genuine wrong
 * password — a timing distinguisher the identical response body does not have.
 * It is the right trade twice over. Verifying a password that is going to be
 * ignored would turn the lockout into a CPU amplifier, one request buying one
 * scrypt, so the cheap answer is the point of refusing early. And the timing
 * reveals only that this address is locked, which says nothing about whether an
 * account exists: the counter keys on the submitted string, so an address with
 * no account locks exactly like one with an account.
 */
const signInLockoutBefore = createAuthMiddleware(async (ctx) => {
  if (ctx.path !== SIGN_IN_EMAIL_PATH) {
    return;
  }
  const email = readSignInEmail(ctx.body);
  if (email === null) {
    return;
  }

  const now = new Date();
  const { isLocked } = await readSignInLockState(email, now);
  if (!isLocked) {
    return;
  }

  await recordSignInAttempt(email, "blocked", now);
  throw APIError.from("UNAUTHORIZED", CREDENTIALS_REJECTED);
});

/**
 * Records the outcome of a finished sign-in, which is both the counter the hook
 * above reads and the failed-attempt log the A09 half of issue #112 asks for.
 *
 * `hooks.after` runs on a *failed* sign-in and not only a successful one, which
 * is the property that makes one hook enough. `dist/api/dispatch.ts` catches an
 * `APIError` thrown by an endpoint handler, parks it on
 * `ctx.context.returned`, and runs the after-hooks before turning it into a
 * response — so the same hook sees both outcomes, and the `APIError`'s
 * `statusCode` is what tells them apart. Reading `returned` this way is the
 * library's own pattern; the admin plugin's `/list-sessions` hook does it
 * through `getEndpointResponse`, which is the same field with success-only
 * filtering this hook must not have.
 *
 * `classifySignInOutcome` decides what a given status means, so which failures
 * count towards a lock is stated and tested in one pure place rather than
 * spread through this wiring.
 */
const signInLockoutAfter = createAuthMiddleware(async (ctx) => {
  if (ctx.path !== SIGN_IN_EMAIL_PATH) {
    return;
  }
  const email = readSignInEmail(ctx.body);
  if (email === null) {
    return;
  }

  const returned: unknown = ctx.context.returned;
  if (returned === undefined || returned === null) {
    return;
  }

  const outcome = classifySignInOutcome(
    isAPIError(returned) ? returned.statusCode : null,
  );
  if (outcome === null) {
    return;
  }

  await recordSignInAttempt(email, outcome, new Date());
});

export const auth = betterAuth({
  database: prismaAdapter(db, { provider: "postgresql" }),
  // No `session.cookieCache` here (issue #114): enabling it later requires
  // also re-checking `user.banned` on the cached path, because
  // `src/lib/require-user.ts`'s guard only re-reads that flag on the
  // uncached, per-request session lookup this config currently produces.
  emailAndPassword: {
    enabled: true,
    disableSignUp: true,
  },
  rateLimit: RATE_LIMIT,
  hooks: { before: signInLockoutBefore, after: signInLockoutAfter },
  // `nextCookies` has to stay last in the list: it converts the cookies the
  // preceding plugins set into Next.js cookie writes.
  plugins: [
    admin({
      ac: accessControl,
      roles: { [ADMIN_ROLE]: adminAccess, [STAFF_ROLE]: staffAccess },
      defaultRole: STAFF_ROLE,
      adminRoles: [ADMIN_ROLE],
    }),
    nextCookies(),
  ],
});

/**
 * The route handler pair mounted at `/api/auth/[...all]`. It is built here
 * rather than in the route file so that `better-auth` keeps a single import
 * site on the server, as the seam rules require.
 */
export const authRouteHandlers = toNextJsHandler(auth);
